version: '3'
services: 
  go-first:
    build: .
    security_opt:
      - seccomp:unconfined
    entrypoint: dlv debug local/myorg/go-first -l 0.0.0.0:2345 --headless=true --log=true -- server
    volumes:
      - .:/opt/go/src/local/myorg/go-first
    ports:
      - "2345:2345"
    expose:
      - "2345"